### ISSUE TITLE
Create a Docker image for running Zonation 

### ISSUE THREAD

**Issue by jlehtoma** [cbig/zonation-core#21]
Zonation can currently only be compiled (and run) using an old system (e.g. Ubuntu 14.04, maybe 16.04) with old enough libraries (most notably Boost and Qt). As suggested e.g. @Martin-Jung in #19 , building a Docker image around system requirements Zonation needs would enable running Zonation on modern systems as well.

This issue is for discussing what it would take to build such an image and/or on the implementation details. Contributions of all sorts welcome!

**Comment by Martin-Jung** [comment]
Thanks for opening this issue! 

I think what we need to move this forward is detailed information on what libraries and **versions** (boost, qt, etc ...) are required to compile zonation. I can see some information already here (https://github.com/cbig/zig4-compilation-scripts), however they did not work for me when I tried them on a cloud VM, possibly because some libraries were to "new". 

What the docker image in my opinion should provide:
-  A linux based distribution. As modern as possible. Ubuntu 14.04 is - as of today (31/03/2019) - not anymore supported and most cloud computing services will likely drop the images soon.
- A ready to run installation of zonation (latest stable release) with all required libraries
- R preinstalled as well as latest "zonator" r package stable release
- Working installation of ztools
- (Tutorial files?)

**Comment by jlehtoma** [comment]
Thanks for the input @Martin-Jung ! I think the things you list above would indeed make a sensible image. Two quick comments:

> I think what we need to move this forward is detailed information on what libraries and versions (boost, qt, etc ...) are required to compile zonation. 

This information is at least partly available, but scattered across various places and notes. Will have to come back to this.

> A linux based distribution. As modern as possible. Ubuntu 14.04 is - as of today (31/03/2019) - not anymore supported and most cloud computing services will likely drop the images soon.

Relating to your initial question at #19 , it should be possible to get Zonation [compiled on Ubuntu 16.04](https://github.com/cbig/zonation-core/issues/15#issuecomment-287812051). The isn't of course so much the version of the OS as the versions of the dependency libraries. On more recent versions of Ubuntu we would have to compile the older versions of Boost and the like, and then link against those specific libraries when doing the dynamic build [1]. I suppose one can do this also within Docker images.

[1] Doing a static build would be of course another option, but would probably take more poking around with the (largely undocumented) compilation tool chain.

**Comment by jlehtoma** [comment]
I had a quick look at this and I think the main dependencies are:
+ Qt <= 4.8
+ 1.48 >= Boost <= 1.55
+ libfftw-dev (not sure if specific version is needed, but was testing with 3.3.7-1)
+ gdal-dev (not sure if specific version is needed, but was testing with 2.2.3+dfsg-2)

I spun up a vanilla VM (Ubuntu 18.04 LTS) on Virtualbox and did the following:

### 1. Update system and install deps
```
sudo apt-get update
sudo apt-get install cmake build-essential unzip libfftw3-dev libqwt-dev libgdal-dev
```

### 2. Build Boost 1.55
```
mkdir -p zonation/vendor/boost && cd zonation/vendor/boost
wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz
tar -xvf boost_1_55_0.tar.gz
cd boost_1_55_0
./bootstrap.sh --prefix=../../../boost
./b2 install
```

### 3. Get Zonation sources
```
cd ~
git clone https://github.com/cbig/zonation-core.git zonation/zonation-core-master
```

### 4. Try building Zonation

```
mkdir -p zonation/build && cd zonation/build
# Set BOOST_ROOT to point to Boost installation directory
cmake ../zonation-core-master -DBOOST_ROOT=/home/jlehtoma/zonation/boost/
```

`cmake` does find the custom Boost installation okay:

```
[...]
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   chrono
--   thread
--   date_time
--   atomic
[...]
```

but the build fails with the familiar error:

```
jlehtoma@z-dev:~/zonation/build$ make    
[  1%] Generating moc_observer.cxx
[  2%] Generating moc_core.cxx
[  4%] Generating moc_io_arg.cxx
[  5%] Generating moc_manager.cxx
Scanning dependencies of target zig4lib
[  7%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/core.cpp.o
[  8%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_load.cpp.o
[ 10%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_save.cpp.o
[ 11%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o
[ 13%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o
/home/jlehtoma/zonation/zonation-core-master/zig4lib/io_admu_load.cpp:21:10: fatal error: boost/spirit/home/phoenix/container.hpp: No such file or directory
 #include <boost/spirit/home/phoenix/container.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
zig4lib/CMakeFiles/zig4lib.dir/build.make:178: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o' failed
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/all' failed
make[1]: *** [zig4lib/CMakeFiles/zig4lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

The weird things is that the header file `<boost/spirit/home/phoenix/container.hpp>` does exist in `/home/jlehtoma/zonation/boost/include`. More over, the two previous includes in `zig4lib/io_admu_load.cpp` are found just fine:

```
[...]
#include <boost/spirit/include/qi.hpp>
#include <boost/spirit/include/phoenix.hpp>
#include <boost/spirit/home/phoenix/container.hpp>
[...]
```

The only thing I could think of was that the compiler is still including headers from system installation location (`libboost1.65-dev:amd64 (1.65.1+dfsg-0ubuntu5)` is installed) as `<boost/spirit/include/qi.hpp>` and `<boost/spirit/include/phoenix.hpp>` are found in `/usr/include/` but `<boost/spirit/home/phoenix/container.hpp>` isn't. However, looking at cmake's `INCLUDE_DIRECTORIES` property, I get the following:

```
-- dir='/home/jlehtoma/zonation/build/cmake_generated'
-- dir='/home/jlehtoma/zonation/zonation-core-master'
-- dir='/home/jlehtoma/zonation/zonation-core-master/zig4'
-- dir='/home/jlehtoma/zonation/zonation-core-master/zig4/core'
-- dir='/usr/include/qt4'
-- dir='/usr/include/qt4/QtNetwork'
-- dir='/usr/include/qt4/QtCore'
-- dir='/usr/include/gdal'
-- dir='/home/jlehtoma/zonation/boost/include'
```

I have no ideas at this point how to proceed.

**Comment by jlehtoma** [comment]
I did more check by renaming `#include <boost/spirit/include/phoenix.hpp>` in `zig4lib/io_admu_load.cpp` and seeing where the renamed file needs to be for the compiler to find. Result: it needs to be in the system include dir `/usr/include/boost/spirit/include/`. I.e. the include dirs are not being handled properly.

**Comment by jlehtoma** [comment]
The problem was that the `CMakeLists.txt` file in `zig4` target was still looking for system version of boost. Adding the following in before line 55 in `zonation-core/zig4/CMakeLists.txt` solves this sub-issue (note that `[LOCATION]` refers to wherever the sources are on the system:

```
set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "[LOCATION]/zonation/boost/include")
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "[LOCATION]/zonation/boost/lib")
```

This is results in compilation advancing further, but still erroring with *very* nasty looking messages relating to Boost spirit.

**Comment by hkujala** [comment]
In case it's useful, @wkmor1 has a built docker container that has Zonation:
https://hub.docker.com/r/wkmor1/eco-dev/dockerfile

For building your own:
https://github.com/wkmor1/eco-dev/tree/trusty

Not sure how helpful these are if there has been very resent changes to how relevant libraries are supported. But it did seem to work fine just few weeks ago.

**Comment by wkmor1** [comment]
> In case it's useful, @wkmor1 has a built docker container that has Zonation:
> https://hub.docker.com/r/wkmor1/eco-dev/dockerfile
> 
> For building your own:
> https://github.com/wkmor1/eco-dev/tree/trusty
> 
> Not sure how helpful these are if there has been very resent changes to how relevant libraries are supported. But it did seem to work fine just few weeks ago.

~~Well, actually that container is running a zonation binary that was built in Jan 2016 https://bintray.com/wkmor1/binaries/zonation from this docker image: https://github.com/wkmor1/build-zig4 which won't currently build due to the issues with updated boost etc above. It still runs in ubuntu-trusty though.~~

**Update**

Turns out my trusty-based zonation docker image does still build fine. Have added it to dockerhub. It can be run with:

`docker run wkmor1/build-zig4 zig4 -v`

**Comment by jlehtoma** [comment]
Thanks @hkujala and @wkmor1 ! I tried to run the container on my local machine and got [this error](https://github.com/wkmor1/build-zig4/issues/1) (looks like a minor `PATH` issue).

The only potential problem I see here is that Docker might drop support for trusty at some point. Couldn't find anything on this with quick googling, so probably not an immediate issue.

**Comment by wkmor1** [comment]
Yeah @jlehtoma PATH was wrong sorry about that. Fixed now. Sorry for the delay. Some or one of the recent updates to zonation-core seems to have broken the build so have reverted back to a previous commit for the image.

**Comment by jlehtoma** [comment]
Thanks, will test this out a bit later. Would be great if the latest version of Zonation would work.

**Comment by jlehtoma** [comment]
@wkmor1 coming back to this after a while. Did you update the docker image on dockerhub after the PATH fix? I'm still getting the same error, so was just wondering. If you didn't, would be great if you had the time to re-build the image.

**Comment by wkmor1** [comment]
I just ran this and it seemed to work fine?

`docker run wkmor1/build-zig4 zig4 -v`

Is this not the output you get? -->

```
Unable to find image 'wkmor1/build-zig4:latest' locally
latest: Pulling from wkmor1/build-zig4
a7344f52cb74: Pull complete 
515c9bb51536: Pull complete 
e1eabe0537eb: Pull complete 
4701f1215c13: Pull complete 
490ae7d7606e: Pull complete 
c887ca244c1d: Pull complete 
Digest: sha256:a8a72938e65a58a99bf761b9a19dac07dbb32b4213c4c5c7e567f3685af7a458
Status: Downloaded newer image for wkmor1/build-zig4:latest

    zig4 version: 4.0.0_compact, build: Jun  5 2019 09:12:43

    zig4 - Zonation computational core
    Copyright (C) 2011-2014 Conservation Biology Informatics Group
    Copyright (C) 2004-2011 Atte Moilanen

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by jlehtoma** [comment]
Ah, my docker-noob-bad. I of course had the old image lurking around on disk so I wasn't really pulling a latest version. Works like expected, thanks and sorry!

**Comment by jlehtoma** [comment]
As far as I can tell, the Docker image provided by @wkmor1 above should do the trick, so closing this issue.
